export const ErrorCodeEnum = {
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",

  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",

  AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_REQUESTS: "AUTH_TOO_MANY_REQUESTS",
  AUTH_UNAUTHRORIZED_ACCESS: "AUTH_UNAUTHRORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",

  // Acess Control Error
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",

  // Validation and Resource Error
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  // System Error
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // custom Http Error
  CUSTOM_HTTP_ERROR: "CUSTOM_HTTP_ERROR",
} as const

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum
